all: FindDevices NewAddress Car FindMagnet FindMaxSpeed FindReducer GetError GetInfo GetSpeedM_S GetSpeedPWM GetSpeedRPM GetStop GetSum SetDirection SetError SetSpeedM_S SetSpeedM_S_Stop SetSpeedPWM SetSpeedPWM_Stop SetSpeedRPM SetSpeedRPM_Stop SetStopNeutral

FindDevices             :FindDevices.cpp ../iarduino_I2C_Motor.cpp
NewAddress              :NewAddress.cpp ../iarduino_I2C_Motor.cpp
Car                     :Car.cpp ../iarduino_I2C_Motor.cpp
FindDevices             :FindDevices.cpp ../iarduino_I2C_Motor.cpp
FindMagnet              :FindMagnet.cpp ../iarduino_I2C_Motor.cpp
FindMaxSpeed            :FindMaxSpeed.cpp ../iarduino_I2C_Motor.cpp
FindReducer             :FindReducer.cpp ../iarduino_I2C_Motor.cpp
GetError                :GetError.cpp ../iarduino_I2C_Motor.cpp
GetInfo                 :GetInfo.cpp ../iarduino_I2C_Motor.cpp
GetSpeedM_S             :GetSpeedM_S.cpp ../iarduino_I2C_Motor.cpp
GetSpeedPWM             :GetSpeedPWM.cpp ../iarduino_I2C_Motor.cpp
GetSpeedRPM             :GetSpeedRPM.cpp ../iarduino_I2C_Motor.cpp
GetStop                 :GetStop.cpp ../iarduino_I2C_Motor.cpp
GetSum                  :GetSum.cpp ../iarduino_I2C_Motor.cpp
NewAddress              :NewAddress.cpp ../iarduino_I2C_Motor.cpp
SetDirection            :SetDirection.cpp ../iarduino_I2C_Motor.cpp
SetError                :SetError.cpp ../iarduino_I2C_Motor.cpp
SetSpeedM_S             :SetSpeedM_S.cpp ../iarduino_I2C_Motor.cpp
SetSpeedM_S_Stop        :SetSpeedM_S_Stop.cpp ../iarduino_I2C_Motor.cpp
SetSpeedPWM             :SetSpeedPWM.cpp ../iarduino_I2C_Motor.cpp
SetSpeedPWM_Stop        :SetSpeedPWM_Stop.cpp ../iarduino_I2C_Motor.cpp
SetSpeedRPM             :SetSpeedRPM.cpp ../iarduino_I2C_Motor.cpp
SetSpeedRPM_Stop        :SetSpeedRPM_Stop.cpp ../iarduino_I2C_Motor.cpp
SetStopNeutral          :SetStopNeutral.cpp ../iarduino_I2C_Motor.cpp
clean:
	rm -f FindDevices NewAddress Car FindMagnet FindMaxSpeed FindReducer GetError GetInfo GetSpeedM_S GetSpeedPWM GetSpeedRPM GetStop GetSum SetDirection SetError SetSpeedM_S SetSpeedM_S_Stop SetSpeedPWM SetSpeedPWM_Stop SetSpeedRPM SetSpeedRPM_Stop SetStopNeutral
